# Generated by Django 4.0.3 on 2022-03-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chatroom_invitations',
            field=models.ManyToManyField(related_name='invited_users', to='chat.chatroom'),
        ),
    ]
